### ISSUE TITLE
Emoji remove link images

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/nodebb-plugin-emoji#10]
Hi!

Currently when we use emoji the image is contained into a link. I've never seen this behavior before, can you disable it and/or add an option? This is confusiung for my users.

Thank you!

**Comment by pitaj** [comment]
Can you clarify what you mean? When they click on the emoji it links them to the image? Can you reproduce on community.nodebb.org ?

**Comment by antoine-pous** [comment]
Yeah, i'm currently using the lavender theme and the latest forum/plugin version. When we use an emoji it wrapped into a link, this is really annoying.

```html
<a href="/plugins/nodebb-plugin-emoji/emoji/emoji-one/1f44d.png" target="_blank">
    <img src="/plugins/nodebb-plugin-emoji/emoji/emoji-one/1f44d.png" class="not-responsive emoji-emoji-one emoji--thumbs_up" title=":+1:" alt="👍">
</a>
```
I can't reproduce it on you forum

**Comment by pitaj** [comment]
What composer are you using? Make sure the emoji plugin is last in the priority. The property can be configured on the acp plugins page.

**Comment by antoine-pous** [comment]
It's already the last plugin :/

![selection_342](https://user-images.githubusercontent.com/7486600/35227787-49652b4e-ff8f-11e7-9a4d-84386f42b539.png)

**Comment by pitaj** [comment]
What composer are you using?

**Comment by antoine-pous** [comment]
nodebb-plugin-composer-default 6.0.7

**Comment by pitaj** [comment]
What other plugins do you have installed? `./nodebb plugins`

**Comment by antoine-pous** [comment]
```sh
         - nodebb-plugin-composer-default
	 - nodebb-theme-lavender
	 - nodebb-plugin-markdown
	 - nodebb-plugin-mentions
	 - nodebb-widget-essentials
	 - nodebb-rewards-essentials
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-emoji-extended
	 - nodebb-plugin-emoji-one
	 - nodebb-plugin-embed-videos
	 - nodebb-plugin-cards
	 - nodebb-plugin-calendar
	 - nodebb-plugin-email-cresmtp
	 - nodebb-plugin-mega-colors
	 - nodebb-plugin-poll
	 - nodebb-plugin-ns-twitch-monitor
	 - nodebb-plugin-sso-battle.net
	 - nodebb-plugin-youtube-embed
	 - nodebb-plugin-custom-pages
	 - nodebb-plugin-ns-custom-fields
	 - nodebb-plugin-emoji`

**Comment by pitaj** [comment]
Disable nodebb-plugin-emoji-extended.

**Comment by antoine-pous** [comment]
Nothing change even after rebuild

**Comment by pitaj** [comment]
My suggestion is to try disabling all plugins (besides the composer and the emoji plugins) and see if that fixes it.

**Comment by BenLubar** [comment]
This is fixed by the fix for #11. It's part of @julianlam's image lazy loading script.

**Comment by barisusakli** [comment]
Hmm I thought @julianlam was removed the lazy loading image stuff in https://github.com/NodeBB/NodeBB/issues/6150

**Comment by julianlam** [comment]
Not quite... I was about to, but I checked the state of anti-jellypotato on the browser front and so far:

* Only Chrome does it
* When I disabled my jellypotato code, Chrome's implementation didn't work anyway 😕

**Comment by pitaj** [comment]
Closed for inactivity
