### ISSUE TITLE
`emoji` class doesn't exist on all emoji

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/nodebb-plugin-emoji#11]
Hi!

Can you use a span instead of img node and add `nodebb-emoji` class on it? When you have a customized line height/font-size the emoji broke the style and we cannot resize/customize them without using a crappy hack.

Thank you!

**Comment by pitaj** [comment]
There is not an issue here that can't be fixed with custom CSS.

Using a span would require ditching alt attributes which would remove a lot of usefulness there. 

With the latest emoji plugin version, there is an emoji class on every emoji. You should be able to change the heights using that and `! important`

**Comment by antoine-pous** [comment]
Using `!important` is bad practice and should be avoided because it break the natural stylesheet cascading.

When you developp a responsive webapp you cannot tell people to break the conventional use of CSS, this is not really logical...

**Comment by pitaj** [comment]
Then you aren't on the latest version of the emoji plugin. You could try avoiding important by gaining specificity elsewhere.

**Comment by antoine-pous** [comment]
Everything seem correctly updated, i've tried to rebuild the front but i've alway the same behavior.
![selection_340](https://user-images.githubusercontent.com/7486600/35227449-6dbcf3f6-ff8e-11e7-9efc-06504b840a3a.png)
![selection_341](https://user-images.githubusercontent.com/7486600/35227506-9a628df8-ff8e-11e7-8ed4-826c96bf14d8.png)

**Comment by pitaj** [comment]
Actually, good catch. Looks like I missed a couple instances where that class should have been added.

**Comment by pitaj** [comment]
Also, you need to deactivate **nodebb-plugin-emoji-extended** while using this plugin.
