### ISSUE TITLE
Weird Error After 1.8.0

### ISSUE THREAD

**Issue by michaelpfaff** [NodeBB/nodebb-plugin-emoji#13]
If I have the ASCII option checked, this plugin removes the space between any bold or italicized word and the previous word.

**Comment by pitaj** [comment]
I'm not able to reproduce this. Can you provide exact reproduction steps?

**Comment by michaelpfaff** [comment]
Yeah, I think something is up with my forum. No emojis are showing up now, even after I rebuild the assets. I tried uninstalling and reinstalling, but that doesn't seem to work either.

**Comment by pitaj** [comment]
Try this: https://github.com/NodeBB/nodebb-plugin-emoji/issues/4#issuecomment-348610842

**Comment by michaelpfaff** [comment]
Going to try that, but also just noticed this error in my log: 

`
Missing translation "admin/menu:plugins/emoji"
`

Might this have something to do with it?

**Comment by pitaj** [comment]
It has absolutely nothing to do with it, I can be 100% confident about that.

**Comment by michaelpfaff** [comment]
@pitaj I think I fixed it after you helped me figure out how to delete all those active but not installed plugins. Emojis seem to work after I reset all those. Thanks!
