### ISSUE TITLE
Issue with v1.8.2

### ISSUE THREAD

**Issue by Starystars67** [NodeBB/nodebb-plugin-emoji#15]
When using this plugin with Version 1.8.2 the £ key and ' key result with :undefined:£:undefined: so there for if writing I've it comes out as I:undefined:':undefined:ve

**Comment by pitaj** [comment]
Does turning off the settings in the ACP stop this error? Can you paste an exact post that results in this issue? (Use a code block please)

**Comment by Starystars67** [comment]
Using the latest version 2.2.1, No Active emoji packs though the android one is installed & what do you mean by ACP?

Resulted output with the plugin enabled: ```which is something that I:undefined:’:undefined:ve wanted to do for years, but for a start```

**Comment by pitaj** [comment]
The ACP is the Admin Control Panel. On the plugin admin page, there are two settings: one for converting thing like `:)` to emoji and one for converting actual native emoji characters to NodeBB emoji. Try turning the second one off, and restarting.

**Comment by Starystars67** [comment]
Is there likely to be a fix for this?

**Comment by pitaj** [comment]
Yep, I plan on fixing this soon.

**Comment by pitaj** [comment]
Fixed in v2.2.2

You can install this version by running 

    npm i --save nodebb-plugin-emoji@2.2.2

In your main nodebb directory.

**Comment by Starystars67** [comment]
Hello, i have installed the update but and the :undefined: issue seems to be resolved but there are no emoji's, any idea on if im missing something

**Comment by pitaj** [comment]
What do you mean by "no emojis"? Does the `:` triggered autocomplete not work? Do things like `:+1:` not get parsed?

**Comment by Starystars67** [comment]
correct it does not work: 
![image](https://user-images.githubusercontent.com/15389482/38707068-a9097cb0-3ea7-11e8-83ee-8c51e01dd72c.png)

comes out with 

![image](https://user-images.githubusercontent.com/15389482/38707085-b82e27a4-3ea7-11e8-8548-fb4d063d6bef.png)

**Comment by Starystars67** [comment]
Yes i have tried this twice and of course: forum.yourthought.co.uk, feel free to take a look

**Comment by pitaj** [comment]
Hi, can you confirm that you have an emoji pack installed and activated? If it's easier, just provide the output of `./nodebb plugins`.

**Comment by Starystars67** [comment]
2018-04-12T23:00:09.636Z [514892] - info: Active plugins:
         - nodebb-plugin-dbsearch
         - nodebb-plugin-desktop-notifications
         - nodebb-plugin-discord-notification
         - nodebb-plugin-beep
         - nodebb-plugin-cards2
         - nodebb-plugin-google-analytics
         - nodebb-plugin-gravatar
         - nodebb-plugin-frontend-async
         - nodebb-plugin-composer-default
         - nodebb-plugin-leaderboard
         - nodebb-plugin-lightbox
         - nodebb-plugin-markdown
         - nodebb-plugin-links-require-login
         - nodebb-plugin-mega-colors
         - nodebb-plugin-important
         - nodebb-plugin-local-image-upload
         - nodebb-plugin-mentions
         - nodebb-plugin-post-revisions
         - nodebb-plugin-ns-spoiler
         - nodebb-plugin-question-and-answer
         - nodebb-plugin-postmentions
         - nodebb-plugin-emoji
         - nodebb-plugin-recent-cards
         - nodebb-plugin-mobile-notification
         - nodebb-plugin-emoji-android
         - nodebb-widget-essentials
         - nodebb-plugin-soundpack-default

**Comment by pitaj** [comment]
Please try rebuilding assets again:

- Click on the button on the ACP Emoji plugin page
- Wait 30 seconds
- Run `./nodebb stop && ./nodebb build && ./nodebb start`

**Comment by Starystars67** [comment]
Yep this has solved it some how, not sure whats different there between your command and what i was doing but hey solved now thank you!

**Comment by Starystars67** [comment]
Unfortunatly this has brought another issue to my attention since getting this going again, every post now has undefined at the bottom, see image for reference or visit my site: 
![image](https://user-images.githubusercontent.com/15389482/38709633-f2118130-3eb3-11e8-832c-dd23d0e1aead.png)

http://forum.yourthought.co.uk/post/215

**Comment by pitaj** [comment]
Just fixed that in v2.2.3

**Comment by Starystars67** [comment]
👍 Updating now, and will get back to you

**Comment by Starystars67** [comment]
Ace Work! Works great just as it used to :)

**Comment by TheWorms** [comment]
Nice job 👌
