### ISSUE TITLE
Inserting an emoji from search results yields :{../name}:

### ISSUE THREAD

**Issue by hkockerbeck** [NodeBB/nodebb-plugin-emoji#16]
If I click on an emoji in the predefined categories (People, Nature, Food, ...), the emoji gets inserted correctly. If I search for a keyword and click on any of the found emoji in the "Search Results" tab, only `:{../name}:` is inserted. Looks like there's a replacement not working.

The problem exists with the latest versions available, NodeBB 1.10.0 and nodebb-plugin-emoji 2.2.3.

**Comment by pitaj** [comment]
Confirmed. I'll fix it soon
