### ISSUE TITLE
Emojis are loading via HTTP instead of HTTPS

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/nodebb-plugin-emoji#20]
I have a nodebb instance running with HTTPS enabled. When loading posts with emojis, I get a chrome warning message for mixed-content.

Viewing the page resources I can see that the emoji plugin is loading the emojis via HTTP instead of HTTPS.

**Comment by julianlam** [comment]
Usually when this happens it is due to your config.json reporting the http url as standard, can you check the value?
