### ISSUE TITLE
Sort Custom Emojis alphabetically?

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/nodebb-plugin-emoji#22]
It would be cool if there was a button that sorted the emojis by a certain rule, like A-Z

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/58146853-fbb3a780-7c25-11e9-8dd8-012987abfcf9.png)
I mean... can we at least get this from A-Z
Also custom emojis seem to be ordered at random! It's not A-Z, not Z-A, and doesn't even show up in the order it was created!

**Comment by pitaj** [comment]
I'm pretty sure the custom emoji are either ordered in the order they show up in the list or in alphabetical order.

Also those letter emoji are very obviously ordered Z-A, left-to-right, top-to-bottom.

**Comment by PatheticMustan** [comment]
The custom emoji is not sorted in the order they are sorted in, or at least not oldest to newest.
Also, I meant to ask if the letters could be switched around from Z-A to A-Z. 
Right now, when I add an emoji, it seems to be randomly placed within the list of emojis.
