### ISSUE TITLE
Plugin assets aren't building

### ISSUE THREAD

**Issue by danstaak** [NodeBB/nodebb-plugin-emoji#23]
NodeBB Version - 1.12.1
nodebb-plugin-emoji version - 2.2.5

When running './nodebb build' NodeBB, the node-plugin-emoji (installed and activated) assets aren't being created. I end up with a folder and contents as follows:

- nodebb website root
  - build
    - public
      - plugins
        - nodebb-plugin-emoji
          - emoji
            - avoid_npm_ignore
  - ...

That leaves me with errors, such as:

Refused to apply style from 'DOMAIN/plugins/nodebb-plugin-emoji/emoji/styles.css?v=k2vf88eesj0' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

When I follow the URL, there is not a stylesheet there.

Is there any reason why during a build an 'emoji' folder is created a populated with an empty file called 'avoid_npm_ignore'?

**Comment by pitaj** [comment]
That file exists when the plugin is installed from npm. The purpose of the file is so npm doesn't ignore the empty directory when I publish the plugin.

Essentially, don't worry about it. The problem you're having is that emoji assets haven't been built yet.

Have you tried building emoji assets from the plugin page in the ACP? Make sure that before doing so you have activated the emoji plugin and any emoji packs you want, and rebuilt and restarted nodebb.

**Comment by danstaak** [comment]
@pitaj Thanks for your reply. I'll give that a go. 

When I build the plugin locally, the files are there - but when I deploy the forum and run through an 'automated' build step (which runs the same commands as I do locally), that's when the assets aren't generated which is strange.

The build runs:

- ./nodebb setup
- ./nodebb upgrade
- ./nodebb build

When I inspect the files it's generated, the emoji plugin is empty (but other plugin assets are generated, e.g nodebb-plugin-markdown)

**Comment by pitaj** [comment]
Yes this is because emoji assets aren't built when `./nodebb build` runs for technical reasons.

It should build them when the forum starts up (look for any errors when you start), but if it doesn't you'll have to hit that button.

**Comment by danstaak** [comment]
Ah OK, I understand now (so they should build on ./nodebb start?) - thanks for pointing me in the right direction. I'll see if I can debug from there.

**Comment by danstaak** [comment]
@pitaj I was able to fix this in the end by running `./nodebb start`

I was getting some strange behavior locally when running `build`/`setup` where the plugin seemed to be generating the assets, giving me false debug readings.

I'm also running the forum through a build & release pipeline on Azure DevOps, using environmental variables instead of config.json which I think was contributing somewhat to the problem.

But it's sorted now. Thanks for your advice RE:not creating assets on `./nodebb build` which helped me debug and fix :)
