### ISSUE TITLE
customize our own emojis

### ISSUE THREAD

**Issue by arranka** [NodeBB/nodebb-plugin-emoji#25]
Is there a way for personalized emoji to come first?

For example, in the "custom" package, it goes much further back

I would like it to appear first as an option for emojis

I leave capture

![image](https://user-images.githubusercontent.com/30248115/61007100-558d3f80-a342-11e9-8932-fb600011b7be.png)

I like the emojis that this package brings, but I would like the default emojis to be the personalized ones

Have the option that the emojis that the package brings are in the background

To be able to order which package of emojis go first

thank you

**Comment by arranka** [comment]
I also see the emojis plugins integrated in the global chat

the emojis button can also be seen when you submit a comment in the global chat

![emojis](https://user-images.githubusercontent.com/30248115/61007766-15c75780-a344-11e9-9887-056aea84d589.png)

**Comment by arranka** [comment]
It would be nice to be able to order personalized emojis in order of importance

today by default they are in order by date

So we could put the most important first and the least important at the end

**Comment by pitaj** [comment]
Please put your other requests in different issues
