### ISSUE TITLE
Emojis button also in global chat

### ISSUE THREAD

**Issue by arranka** [NodeBB/nodebb-plugin-emoji#26]
I would like to see the emoji button also in the global chat

Then when you send a message in global chat if you want you can add emoji

regards

![image](https://user-images.githubusercontent.com/30248115/61573937-4ff3d000-aa8d-11e9-9e8b-a2cdc4f443fa.png)

**Comment by barisusakli** [comment]
![image](https://github.com/NodeBB/nodebb-plugin-emoji/assets/2583394/4a57b685-399d-4a01-bc08-3fdea1ca7bc4)
