### ISSUE TITLE
Failed to load emoji metadata

### ISSUE THREAD

**Issue by sharked76** [NodeBB/nodebb-plugin-emoji#28]
Since updating the plugin, I am getting error on the bottom right of my browser:

Failed to load emoji metadata

![image](https://user-images.githubusercontent.com/48071101/61658959-759ef600-ac94-11e9-8013-2fd56877d9e5.png)

**Comment by pitaj** [comment]
Try the following: "Build emoji assets" button on the plugin page in the ACP, wait 30sec, restart and rebuild

**Comment by pitaj** [comment]
closed for inactvity
