### ISSUE TITLE
Display Emoji dialog box in Quill

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-emoji#29]
Hi @pitaj 

When integrating this plugin with Quill, and pushing the "add icon" button, the plugin fails with:
emoji-dialog.js:149 Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of undefined

To fix this, please add:
1. Top of file:
import { active as activeComposer } from 'composer';

2. In toggle, update opener if quill is available:
if ($('[data-uuid="' + composer_1.active + '"] .ql-container.ql-snow'))
                opener = document.querySelectorAll('button.ql-emoji-add-emoji')[0];

Just before:
 var buttonRect = opener.getBoundingClientRect();

3. In ./public/lib/types.d.ts
Add:
declare module 'composer' {
  export var active: string;
}

**Comment by julianlam** [comment]
That would be a hack that only works for Quill, which I don't think we'd want in a plugin. If every plugin had to add in a hack to work with Quill then it's a pretty crappy composer plugin.

Emoji will need to utilise the core methods to add a composer button, I believe it might be manually adding them at this time.

**Comment by PostMidnight** [comment]
If you could give me an example, I'll try to resolve properly.

**Comment by PostMidnight** [comment]
Here is a hack for the 2nd problem:

Description:
Once the fix proposed above is done, and an emoji is selected from the dialog box, we'll hit the following issue:
Uncaught TypeError: t.context.getSelection is not a function

In this function:
quill-nbb.js

$(window).on('action:composer.insertIntoTextarea', function (evt, data) {
		var selection = data.context.getSelection(true);
		data.context.insertText(selection.index, data.value);
		data.preventDefault = true;
	});

I was able to get the emoji to work using the following hack:

```
function toggleForInsert(textarea) {
        toggle($('[data-format="emoji-add-emoji"]').filter(':visible')[0], function (e, name) {
            var text = ":" + name + ": ";
            var quill = $('[data-uuid="' + composer_1.active + '"] .ql-container.ql-snow').data("quill");
            if (quill) {
                var range = quill.getSelection();
                var text_1 = ":" + name + ": ";
                if (range) {
                    if (range.length == 0) {
                        //User cursor is at index
                    }
                    else {
                        //User has highlighted text - deleting and replacing with emoji
                        quill.deleteText(range.index, range.length);
                    }
                    quill.clipboard.dangerouslyPasteHTML(range.index, text_1);
                }
                return;
            }
            var selectionStart = textarea.selectionStart, selectionEnd = textarea.selectionEnd;
            var end = selectionEnd + text.length;
            var start = selectionStart === selectionEnd ? end : selectionStart;
            controls_1.insertIntoTextarea(textarea, text);
            controls_1.updateTextareaSelection(textarea, start, end);
            $(textarea).trigger('input');
        });
    }
```

**Comment by pitaj** [comment]
@julian I do use the built-in methods for buttons: https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/public/lib/emoji.ts#L122

the cause of the first issue is that I try to place the emoji dialog next to the button instead of just at a chosen point on the screen. If the following call passed the event object through, then I could use event.target to get the button element for placement.

I should have added a check to make sure the button actually exists in the first place though.

**Comment by PostMidnight** [comment]
@pitaj not sure if this is a good solution, but maybe its possible to make the emoji window drag-able, and let the user re-position? In that case you won't need coordinates.

**Comment by pitaj** [comment]
@postmidnight the emoji dialog is already draggable. I think placing the dialog near where the mouse is when the button is clicked is the best UX

**Comment by PostMidnight** [comment]
I guess something went wrong when it got integrated with quill as the modal it is not draggable ;)
Maybe its just my setup. I'll try to understand why mañana.

**Comment by PostMidnight** [comment]
It seems that we need to do the following:
First, set draggable="true" in the html line calling the modal.

Second, for the below (emoji-dialog.js), we need jQuery-UI installed. I don't think that is standard in NBB.
            if (dialog.draggable) {
                dialog.draggable({
                    handle: '.top-bar',
                });
            }

Again this could be setup issues, but I did try with pure nbb and just emoji and quill installed.

**Comment by pitaj** [comment]
Yes right now the dialog is only made draggable is jQuery UI is already loaded. It won't load jQUI on it's own because I don't think it's worth it.

**Comment by julianlam** [comment]
I agree, the jQuery UI toolkit is massive for the small functional benefit it brings, and that's why it is not on the client side (only ACP)

**Comment by PostMidnight** [comment]
I wonder, If I display a chat dialog and an emoji dialog at the same time the emoji dialog is fixed, while the chat window is draggable. Moreover, both have the "ui-draggable" class. Maybe the issue is unrelated to jQuery UI.

**Comment by PostMidnight** [comment]
Hi,

My previous proposal was faulty, my apology.
I was able to get the emojis working robustly with just the following changes to toggleForInsert in /public/lib/emoji-dialog.ts.

```
export function toggleForInsert(textarea: HTMLTextAreaElement) {
  //toggle($('[data-format="emoji-add-emoji"]').filter(':visible')[0], (e, name) => {

  let path_to_container = $(textarea).parent();

  toggle(path_to_container.find('button.ql-emoji-add-emoji').filter(':visible')[0], (e, name) => {
    const text = `:${name}: `;
    let quill = path_to_container.find('.ql-container').data('quill');
    if(quill) {
       var range = quill.getSelection();
       const text = `:${name}: `;
       if (range) {
          if (range.length == 0) {
             //User cursor is at index
          } else {
             //User has highlighted text - deleting and replacing with emoji
             quill.deleteText(range.index, range.length);
          }
          quill.clipboard.dangerouslyPasteHTML(range.index, text);
       }
       return;
    }

    const { selectionStart, selectionEnd } = textarea;
    const end = selectionEnd + text.length;
    const start = selectionStart === selectionEnd ? end : selectionStart;

    insertIntoTextarea(textarea, text);
    updateTextareaSelection(textarea, start, end);
    $(textarea).trigger('input');
  });
}

```

**Comment by pitaj** [comment]
I'm fairly certain that code breaks functionality with the default composer.

Once again, there's no way I'm special-casing this for quill. If you want it supported I suggest you work on implementing the API extension I proposed here: https://github.com/NodeBB/nodebb-plugin-emoji/issues/29#issuecomment-514251050

**Comment by PostMidnight** [comment]
Hi @pitaj 
I was hoping to solve the "special case" scenario and get assistance from you guys on the general case,
I'll try, its not that simple for me ;)

**Comment by PostMidnight** [comment]
Hi @pitaj some help please. 
My changes were made in the following function:
toggleForInsert(textarea: HTMLTextAreaElement) {
toggle($('[data-format="emoji-add-emoji"]').filter(':visible')[0], (e, name) => {

The above code may have two issues: 
A. There could be multiple composers, I believe you need to toggle the one that is being used (one may extract said information from the textdata).
B. I don't see a handler here. 
Sorry,my understanding of your system is far from being complete, thanks for understanding.

**Comment by pitaj** [comment]
No I was talking about this portion of my comment:

> I try to place the emoji dialog next to the button instead of just at a chosen point on the screen. If the following call passed the event object through, then I could use event.target to get the button element for placement. https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/formatting.js#L85

Specifically changing that API call to pass through the event object, so I could grab `event.target` which should point to the button.

**Comment by PostMidnight** [comment]
Hi @pitaj 

It looks like my explanation was poorly written, thus allow me to rephrase:
In emoji-dialog.ts, init is called by toggle, and toggle is called by toggleForInsert. 
The fix that I proposed here https://github.com/NodeBB/nodebb-plugin-emoji/issues/29#issuecomment-515995378 is the only one needed to make the plugin work, that is it addresses issue #1 and issue #2. 

As you may note, its a similar workaround to what you proposed, namely, I am using textarea to figure out the path to the buttons, and I am sending that as a parameter to toggle. From that point "opener" in init will be properly defined and thus getBoundingClientRect will return coordinates.

Let me go ahead and propose a slightly better version for toggleForInsert, having the following enhancements:
A. Will not break composer.
B. Validate that the buttons exist prior to launching toggle.

Note that for quill, I am using toggle per editor, while in composer a single toggle is used for all editors. Reason, I wanted to provide 100% compatibility with the existing implementation.

Lastly (and this should probably be reviewed by @julianlam ), I believe it may be beneficial to create two more handlers:
A. emojiPathHandler : Returns path to button, so it may be validated prior to launching toggle
B. emojiToggleHandler: Serves as toggle's callback.
Plugins may then initialize said handlers at start. For example, a handler for composer may look like this:

function emojiPathHandler (textarea) {
   return $('[data-format="emoji-add-emoji"]');
   //Or a slightly better version:
   $('textarea').parents('.composer-container').find('[data-format="emoji-add-emoji"]');
}

function emojiToggleHandler (e, textarea, name) {
   const text = `:${name}: `;
   const { selectionStart, selectionEnd } = textarea;
   const end = selectionEnd + text.length;
   const start = selectionStart === selectionEnd ? end : selectionStart;

   insertIntoTextarea(textarea, text);
   updateTextareaSelection(textarea, start, end);
   $(textarea).trigger('input');
}

Revised code for toggleForInsert:

```
export function toggleForInsert(textarea: HTMLTextAreaElement) {
  let path_to_composer_button = $('[data-format="emoji-add-emoji"]');
  if(path_to_composer_button.length)
     toggle(path_to_composer_button.filter(':visible')[0], (e, name) => {
       const text = `:${name}: `;
       const { selectionStart, selectionEnd } = textarea;
       const end = selectionEnd + text.length;
       const start = selectionStart === selectionEnd ? end : selectionStart;

       insertIntoTextarea(textarea, text);
       updateTextareaSelection(textarea, start, end);
       $(textarea).trigger('input');
       return;
    });

  let path_to_quill_container = $(textarea).parent();
  let path_to_quill_button = path_to_quill_container.find('button.ql-emoji-add-emoji');
  if(path_to_quill_button.length)
    toggle(path_to_quill_button.filter(':visible')[0], (e, name) => {
      let quill = path_to_quill_container.find('.ql-container').data('quill');
      if(quill) {
        var range = quill.getSelection();
        if (range) {
          if (range.length == 0) {
            //User cursor is at index
          } else {
            //User has highlighted text - deleting and replacing with emoji
            quill.deleteText(range.index, range.length);
          }
          const text = `:${name}: `;
          quill.clipboard.dangerouslyPasteHTML(range.index, text);
        }
        return;
      }
    });
}

```

**Comment by pitaj** [comment]
I've made my position on special-casing quill very clear. I'm not going to implement a workaround.

> Validate that the buttons exist prior to launching toggle.

It's doesn't really validate that one of the buttons exists. If neither type of button exists it will still break.

> Uses action:composer.insertIntoTextarea - moves quill related insertion code to the plugin.

I don't know what this means. Are you suggesting replacing this: `$(textarea).trigger('input');`

```
$('textarea').parents('.composer-container').find('[data-format="emoji-add-emoji"]');
```

**Comment by PostMidnight** [comment]
Hi @pitaj 
1. I totally understand about special casing, but without a handler, this is as much as I could do by myself ;)
2. If neither buttons are available, the "if(path_to_composer_button.length || path_to_quill_button.length)" will fail and the emoji dialog will just not come up. I believe its a reasonable solution.
3.  I am not suggesting to replace $(textarea).trigger('input'); For quill, it was enough that you called insertIntoTextArea. That triggered action:composer.insertIntoTextarea. I should have realized that earlier, but it took a long time for me to understand how that mechanism works. See plugin code below.
4. Glad I could help.

In Quill plugin, I did the following:
```

         $(window).on('action:composer.insertIntoTextarea', function (evt, data) {
		let quill = $(data.textarea).parent().find('.ql-container').data('quill');
		if(quill) {
			let range = quill.getSelection();
			//const text = `:${name}: `;
			const text = `${data.value} `;
			if (range) {
				if (range.length === 0) {
					//User cursor is at index
				} else {
					//User has highlighted text - deleting and replacing with emoji
					quill.deleteText(range.index, range.length);
				}
				quill.clipboard.dangerouslyPasteHTML(range.index, text);
			}
		}
		data.preventDefault = true;
	});

	$(window).on('action:composer.updateTextareaSelection', function (evt, data) {
		let quill = $(data.textarea).parent().find('.ql-container').data('quill');
		if(quill) {
			let range = quill.getSelection();
			if (range)
				quill.setSelection(range.index, range.length);
		}
		data.preventDefault = true;
	});

```

**Comment by pitaj** [comment]
> If neither buttons are available, the "if(path_to_composer_button.length || path_to_quill_button.length)" will fail and the emoji dialog will just not come up. I believe its a reasonable solution.

Oops my mistake. Yeah you're right.

I'll try implementing my changes tonight, hopefully it'll work.

**Comment by PostMidnight** [comment]
Before you do anything major, please consider the following: 
We will add a predefined class to the emoji button, either with tpl or by Js via plugin. That class will identify the emoji button and will be editor invariant. Lets call it "ident-emoji-add-emoji"

If we do that, all you'll have to do in the plugin is the following:

```

export function toggleForInsert(textarea: HTMLTextAreaElement) {
  let path_to_button = $('textarea').parents('.composer-container').find('.ident-emoji-add-emoji"]');

  if(path_to_button.length) {
    toggle(path_to_button.filter(':visible')[0], (e, name) => {
       const text = `:${name}: `;
       const { selectionStart, selectionEnd } = textarea;
       const end = selectionEnd + text.length;
       const start = selectionStart === selectionEnd ? end : selectionStart;

       insertIntoTextarea(textarea, text);
       updateTextareaSelection(textarea, start, end);
       $(textarea).trigger('input');
    });
  }
}

```
