### ISSUE TITLE
Close window upon chat minimized / closed

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-emoji#32]
Referencing new hooks added here: https://github.com/NodeBB/NodeBB/issues/7805

In a similar manner to https://github.com/NodeBB/nodebb-plugin-emoji/commit/0d144fbbda0cbd22fffbed41861441790f1c9cc1, kindly consider doing the same for chats, as follows:

In public/lib/emoji-dialog.ts line 153
Replace:
`$(window).on('action:composer.discard action:composer.submit action:composer.minimize', close);
`

With:
`$(window).on('action:composer.discard action:composer.submit action:composer.minimize action:chat.minimized action:chat.closed', close);`

**Comment by pitaj** [comment]
Why should opening a chat window close the emoji dialog?

**Comment by PostMidnight** [comment]
Actually, these events are fired upon "closing" or "minimizing" the chat dialog, not when it is opened.

Using emojis with chat is very useful, and in mobile resolution where the screen is small, its better not to clutter. To that end, I believe that in a similar manner to composer, closing /minimizing should "hide" the emoji dialog.

**Comment by pitaj** [comment]
I wasn't aware that it was possible to open the emoji dialog from the chat, and I can't find any way to do so.

**Comment by PostMidnight** [comment]
With composer its not supported. However Redactor and Quill editors may be configured to display the chat window with the emoji button. You'll have to switch to one of these editors, and quill is the better choice.

However, please be careful and back up your db if you want to see emojis in action with quill. You may not be able to revert back once you'll switch.
