### ISSUE TITLE
Plugin does not seem to be working on NodeBB 1.14.2

### ISSUE THREAD

**Issue by SenkJu** [NodeBB/nodebb-plugin-emoji#39]
I have just updated my forum to the latest version (1.14.2) and found that this plugin seems to be incompatible now. Due to an error that occurs whenever the composer is opened, it is no longer possible to create new posts or reply to existing ones. The following error is reported in the console:
![error](https://axolotl.pics/buTsWg3V.png?key=pP0YM5hpQXuxsh)
I have disabled the plugin for now and that seems to have fixed the problem. 

Additional information:
NodeBB version: 1.14.2
nodebb-plugin-emoji version: 3.3.2
I am using custom emojis.

**Comment by psychobunny** [comment]
Hi could you try again? emoji should be downgraded to 3.3.1, I made a mistake when creating the latest version

**Comment by pitaj** [comment]
Just published 3.3.3, hopefully that works.

**Comment by SenkJu** [comment]
> Hi could you try again? emoji should be downgraded to 3.3.1, I made a mistake when creating the latest version

Thanks. I have reinstalled the plugin thereby downgraded to 3.3.0. Everything seems to be working now.
