### ISSUE TITLE
I get :undefined:’:undefined: in composer until I uninstall the plugin

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/nodebb-plugin-emoji#4]
No idea what is going on and I am running node bb 1.7.0

**Comment by pitaj** [comment]
Try a few things:

- Disable emoji-extended
- Pull latest NodeBB master
- `./nodebb stop`, `./nodebb build`, `./nodebb start`
- In the ACP plugin settings page, click Rebuild Assets

**Comment by jimmykane** [comment]
@pitaj thanks a lot for replying! Somehow I feel bad for reporting this bug because: 
a) I have no control over the source
b) I am only admin
c) The auto-update system somehow gets only the tags or a state of master after it sees that there is a tag/release publish. For example, I am stuck from what I realize in some commits after v1.7.0

Hope this makes sense.... 

Previously before installing this over the -extend version I first uninstalled and restarted node. 
I tried 2 times uninstalling/restarting etc this plugin and got the same state. 

I believe it's better to leave this issue open or close it but I will track from my side the cause as well. 


PS. I think we are here somewhere in master. See https://github.com/NodeBB/NodeBB/issues/6080

**Comment by pitaj** [comment]
Oh, so you have no way of running commands on the server? Who is the host? If it's hosted on the NodeBB SaaS, I could take a look there.

**Comment by jimmykane** [comment]
@pitaj  I ll try somehow to solve this. But it's a big organization, it's my hobby job as normally I am a full stack. So imagine my position. I'll get back with more info. Feel free to close this.

**Comment by scottalanmiller** [comment]
Same issue here.

**Comment by julianlam** [comment]
Can you let us know the output of `./nodebb plugins`?

If you can get a dev instance up with the production data, you can try deactivating all of the third-party plugins and seeing if the issue is resolved.

**Comment by scottalanmiller** [comment]
[root@lnj-lnx-mangolassi mangolassi]# ./nodebb plugins
1/12 20:22:14 [10629] - info: Active plugins:
     - nodebb-theme-persona
     - nodebb-plugin-mentions
     - nodebb-plugin-markdown
     - nodebb-plugin-dwnvtr
     - nodebb-plugin-color
     - nodebb-plugin-outside
     - nodebb-plugin-category-info
     - nodebb-plugin-designer
     - nodebb-plugin-finder
     - nodebb-widget-essentials
     - nodebb-plugin-spam-be-gone
     - nodebb-plugin-emailer-mailgun
     - nodebb-plugin-google-analytics
     - nodebb-plugin-dbsearch
     - nodebb-plugin-emoji
     - nodebb-plugin-composer-default
     - nodebb-plugin-emoji-one
     - nodebb-plugin-youtube-embed
     - nodebb-plugin-imgbed
     - nodebb-plugin-question-and-answer
     - nodebb-plugin-embed-gmap
     - nodebb-plugin-imgur
     - nodebb-plugin-shortcuts
     - nodebb-plugin-soundpack-default


________________________________

**Comment by jimmykane** [comment]
Hehe I see: 

`nodebb-plugin-soundpack-default` nice! 

FYI  I don't have many plugins in common and no emoji plugins installed except this one. 
However, I have uninstalled the previous ones before installing this one. 

Same theme persona, dbsearch in common.

**Comment by scottalanmiller** [comment]
Should I remove the soundpack?  We didn't want any sounds, but we had some issues when removing it long ago, so left it in and ignored it :)  A few of those plugins are there for legacy reasons, not because we were using them.  Most we use, but not sounds.

________________________________

**Comment by pitaj** [comment]
Don't remove plugins packaged in NodeBB core.

**Comment by scottalanmiller** [comment]
That's what I thought.  LOL  That's why it is there.

________________________________

**Comment by pitaj** [comment]
@scottalanmiller can you try running the following steps, trying the emoji after each step:

- `./nodebb stop && ./nodebb build && ./nodebb start`
- Rebuild Assets in the plugin ACP page
- `./nodebb stop && ./nodebb build && ./nodebb start`
- `./nodebb stop`, Delete the `node_modules` directory and `./nodebb start`
- `./nodebb stop`, Delete the `build` directory and `./nodebb build && ./nodebb start`
- Rebuild Assets in the plugin ACP page
- `./nodebb stop && ./nodebb build && ./nodebb start`

That's all I've got. If those steps don't solve it, I might just take a look at your server myself to see if I can figure it out.

**Comment by scottalanmiller** [comment]
Okay cool.  We are an extremely busy side, especially in these hours, so I'll have to wait until this evening.  It's Friday, which oddly means our busiest day of the week, but only for another four hours.  Then we crash (in traffic, not the site) and are at near zero traffic for much of the evening, and get busy again around 10PM EST.  So I have an evening window where a few seconds down won't be a big issue.



________________________________

**Comment by pitaj** [comment]
Alright great. I just wanted to add one more thing:

- Make sure `nodebb-plugin-emoji-one` and `nodebb-plugin-emoji` are both activated

Which I've also edited into the previous comment

**Comment by scottalanmiller** [comment]
They are.  I stepped through those a few times (installing, activating, uninstalling, rinse, repeat.)  I would do uninstall, test.  Then install, test.  Then activate the emoji, test.  Then activate the emoji-one, test. In case it worked somewhere along the path and not later. But it stayed the same with :) being just a colon and paren each time.

________________________________

**Comment by scottalanmiller** [comment]
Hey we have a lead.  Well sort of.  One other new issue cropped up this morning that we just found.  When we enter a URL the space in front of it disappears when posting.


Example: Hey check out google.com


We get: Hey check outgoogle.com


Happens every time.  But just started with the 1.7.1 update.

________________________________

**Comment by pitaj** [comment]
I just noticed that you don't have the android emoji pack installed. It should have been installed with the upgrade to v1.7.1

What version of node and npm do you have installed? You can use `./nodebb info` to output some useful information.

**Comment by pitaj** [comment]
As to that issue you mentioned, I can't reproduce it on community.nodebb.org.

Maybe it's one the embed plugins you're using?

**Comment by scottalanmiller** [comment]
That was it.  It was never installed and apparently it is required.  I just installed that and immediately it started working.

________________________________

**Comment by jimmykane** [comment]
So we need also the packs ?

**Comment by scottalanmiller** [comment]
Just that one, I guess?  I have now Android and One.  Nothing else.

________________________________

**Comment by pitaj** [comment]
You don't need to leave emoji-android activated. The issue is caused by a default plugin not being installed automatically for some reason.
