### ISSUE TITLE
Convenient dialog to view and insert all available emoji not showing emojis

### ISSUE THREAD

**Issue by djschilling** [NodeBB/nodebb-plugin-emoji#43]
In my installation i have activated this plugin and nodebb-plugin-emoji-one.

The emojis are shown in posts, but the dialog to view emojis shows none of them.

This issue occured after updating to the newest nodebb version.

What could be the issue there?

Here the forum can be looked up: https://forum.church.tools/

**Comment by pitaj** [comment]
Include versions please:

- plugin
- NodeBB
- Node
- browser
- database

**Comment by pitaj** [comment]
When I visit your site, the dialog appears to be working:
![image](https://user-images.githubusercontent.com/803701/109325740-84a43d80-7813-11eb-87ef-de705e4f4570.png)

Can you provide a screenshot showing what you see? Note that images load into the dialog lazily, so there may be a second or two that it'll be blank while the images load in.

**Comment by djschilling** [comment]
nodebb-plugin-emoji: 3.5.0-0 
nodebb-plugin-emoji-one: 2.0.5 
NodeBB: 1.16.2
Node: v12.21.0
browser: Chrome
Redis Version 4.0.9

wow thats interesting. For me its still not showing up:
<img width="1407" alt="Bildschirmfoto 2021-02-26 um 17 31 59" src="https://user-images.githubusercontent.com/3503166/109327360-8b08d880-7858-11eb-8e88-1b91285c52b2.png">


In the devtools i can see the following error:

```
Failed to load resource: the server responded with a status of 404 ()
require.js:143 Uncaught Error: Script error for "hooks"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```

Maybe it has something to do with it.

**Comment by pitaj** [comment]
3.5.0-0 is a prerelease version, I don't know how you ended up with that but you should install 3.5.0 instead.

That's not causing your issue though. Have you tried hard refreshing (Ctrl+F5) or clearing your cache?

**Comment by djschilling** [comment]
it was the browser cache. thanks.

Is still would say that it is a bug cause my users will also run into this.
But i'm not sure if it is on this repos side or on nodebb.

**Comment by pitaj** [comment]
The image sources [use the NodeBB cache-buster](https://github.com/NodeBB/nodebb-plugin-emoji/blob/68d7be8fd398592a0f5e2958f6a8c3c0778ad81d/public/lib/emoji.ts#L13) and so does [the metadata fetch](https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/public/lib/emoji.ts#L48)

So a rebuild and restart should cause your browser to pull a new version. Whether your browser actually does is up to it.

I think the only case where your users could see this is if they used the site between when when you installed emoji and when you built emoji assets.
