### ISSUE TITLE
Custom image emojis not loading in posts (domain is set to localhost)

### ISSUE THREAD

**Issue by skeddles** [NodeBB/nodebb-plugin-emoji#47]
I installed the plugin via the admin panel, then went to the emoji page and clicked the pencil and added a few emoji.

When I click emoji in the post editor, I see the custom emoji icons. I click and it adds the emoji code like `:smile:`, but then when I post it, the image does not load.

The url appears to be: `https://localhost/plugins/nodebb-plugin-emoji/emoji/customizations/655dbdb4-4eaf-43b4-8030-82d0608f870f-ayy.png?v=kgfcrdm1id4`

I'm not sure why, but it's setting the location to localhost, rather than my domain. If I change the url to my domain and load that in my browser it does work, so it's just that it's putting localhost that's the problem.

**Comment by pitaj** [comment]
The "url" value in config.json must be set to the address at which you access your forum.

**Comment by skeddles** [comment]
changing the value to the url of my forum solved the issue
