### ISSUE TITLE
use emoji images from CDN

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-emoji#49]
allow serving emoji images from cdn, using config.assetBaseUrl if possible
https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/lib/parse.ts#L77

**Comment by barisusakli** [comment]
It seems they are served from `/plugins/nodebb-plugin-emoji/emoji/android/1f642.png"` and not using nginx as well

**Comment by pitaj** [comment]
Nginx scaling config does cover the plugins directory

**Comment by barisusakli** [comment]
ok, just need to switch over to config.assetBaseUrl then so they are served from `/assets/plugins/nodebb-plugin-emoji/...` by default. Custom plugin change that value to point to their cdn in `filter:config.get` so the url will point to `http://cdn.com/assets/plugins/nodebb-plugin/emoji/`  https://github.com/NodeBB/NodeBB/commit/9adaccd0366ce93ed1685aecc288bf5a238d3a26

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-emoji/pull/50
