### ISSUE TITLE
Emoji Plugin Does Nothing

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/nodebb-plugin-emoji#5]
We've installed the NEW emoji plugin as well as the -one emoji set several times.  We've removed all old emoji packages.  We've not had emoji working for many months.  The NEW emoji plugin seems to do absolutely nothing except alter the "undefined" issue.

**Comment by pitaj** [comment]
I'm gonna go ahead and close this since it appears to be remedied, or at least not an issue with the emoji plugin itself.
