### ISSUE TITLE
no emoji are loaded

### ISSUE THREAD

**Issue by tehspaceg** [NodeBB/nodebb-plugin-emoji#6]
```
4/12 16:07:44 [11945] - error: /topic/26/the-funnies/1012
 Error: ENOENT: no such file or directory, open '/var/www/nodebb/forums/node_modules/nodebb-plugin-emoji/build/emoji/table.json'
    at Error (native)
```

I was able to resolve this manually with some black magic (stopping the service, manually reinstalling the emoji plugin from npm, building, starting the service, building assets in the admin panel, etc). BUT, these actions shouldn't be needed. I'd expect during an upgrade / install that the emoji are built properly with no admin effort.

**Comment by pitaj** [comment]
What version of the plugin?

That's weird, because the plugin [specifically checks if the file exists](https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/lib/index.ts#L40) on startup and builds the emoji assets if not.

**Comment by tehspaceg** [comment]
2.0.5

Though looking at the repo, I see 2.0.7 as latest. npm is pulling 2.0.5 though

**Comment by pitaj** [comment]
2.0.6 and 2.0.7 only fixed some styling issues, every change was client-side only. So shouldn't make a difference.

I ran multiple tests for from-scratch installs, I'm fairly certain that if there was an issue in that case, I would have caught it. As for upgrades, I can be as confident there, seems like there have been several issues with upgrades. 

Upgrade issues are a problem in core, though, not with this plugin. If you can't provide reproduction steps then I can't really help.

**Comment by tehspaceg** [comment]
No problem, I don't know how it reproduced either. I can say that the "new" emoji plugin didn't upgrade to v2 until I manually upgraded it with npm. We can close the ticket though, since I have no idea how to reproduce, what triggered it, etc.

**Comment by pitaj** [comment]
If might help if you provide the exact commands you used to upgrade. There may have been a misstep somewhere?

**Comment by tehspaceg** [comment]
I followed the steps in the user guide for the 1.7.0 -> 1.7.1 path ```git fetch && git reset --hard origin/v1.7.x```

I did run into an issue where eslint was not upgrading properly, so maybe something broke in the upgrade process during core? That might explain some of the weirdness I am running into.

**Comment by pitaj** [comment]
Yeah that was most likely what caused this. I'm gonna close but I can open if anyone else runs into this.
