### ISSUE TITLE
why load error when I add a emoji

### ISSUE THREAD

**Issue by Weeeendi** [NodeBB/nodebb-plugin-emoji#60]
![image](https://user-images.githubusercontent.com/34105711/231384510-17a9398f-13dd-42c5-93e0-33da3ef9137a.png)
There is a graph sign always on left of emoji, how to resolve this.

this is my package.json context
```
 "nodebb-plugin-emoji": "^5.0.5",
 "nodebb-plugin-emoji-android": "3.0.0",
 "nodebb-plugin-emoji-one": "^4.0.0",
```

**Comment by pitaj** [comment]
Make sure the "url" property in config.json is set to exactly the URL at which you access the site in your browser.

Open your browser developer tools and check if there are any errors in the console.

**Comment by Weeeendi** [comment]
Thanks for  the reply， I have changed “url” property in config.json to my own site and tried to rebuild nodebb
And I checked my browser developer and found some errors
![image](https://user-images.githubusercontent.com/34105711/231511065-e234c41f-4fac-4ad9-ab54-d4255bdbc755.png)
I noticed some warnings when I build it. Does it matter？
``` shell
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  6aa13e92b5cf7d479e73acdc7c05abf3.js (502 KiB)
  nodebb.min.js (359 KiB)
  admin.min.js (394 KiB)
  4793.dcf82000e95f412bc916.min.js (565 KiB)
  8522.0f42740e78005fe716a3.min.js (501 KiB)
  1083.65b10fecdfacafc29c2c.min.js (800 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  nodebb (359 KiB)
      nodebb.min.js
  admin (394 KiB)
      admin.min.js
```

**Comment by pitaj** [comment]
Are you sure `http://20.222.66.39:4567` exactly matches your browser's URL bar?

**Comment by Weeeendi** [comment]
OK, the browser's URL  has only `20.222.66.39`, that's enough? I used Nginx to Local anti-generation 4567 to 80 port and the "port"  property in config.json that need change to 80?

**Comment by Weeeendi** [comment]
The emoji plugin works, not change "port" property and set URL `http://20.222.66.39:80` is ok. Thanks for your help @pitaj

**Comment by pitaj** [comment]
If the address bar in your browser is just `20.222.66.39`, then you should set "url" in config.json to `http://20.222.66.39`.
