### ISSUE TITLE
After updating to NodeBB 1.7.3 I have again no emoji parsing

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/nodebb-plugin-emoji#9]
Here is an example

<img width="264" alt="screen shot 2018-01-09 at 11 46 55" src="https://user-images.githubusercontent.com/1268723/34714685-e27cb3b8-f532-11e7-918e-dc8628cec556.png">

**Comment by jimmykane** [comment]
I also get undefine:undefined in a lot of places

**Comment by pitaj** [comment]
Make sure nodebb-plugin-emoji-android is installed and try the debugging steps laid out in older issues.

**Comment by jimmykane** [comment]
It is

quick console log: 

```
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at emoji-dialog.js?v=bohcseb734m:1
    at Array.map (<anonymous>)
    at emoji-dialog.js?v=bohcseb734m:1
    at Array.map (<anonymous>)
    at emoji-dialog.js?v=bohcseb734m:1
    at <anonymous>
```

**Comment by jimmykane** [comment]
What other debugging steps should I follow? 
The ones about clearing node modules etc?

**Comment by pitaj** [comment]
Specifically I was taking about these: https://github.com/NodeBB/nodebb-plugin-emoji/issues/4#issuecomment-348610842

**Comment by jimmykane** [comment]
I don't have access on the system unfortunately and it's managed by  nodebb.org

**Comment by pitaj** [comment]
Oh, then definitely contact support@nodebb.org

**Comment by julianlam** [comment]
@jimmykane Can you send an email to the support email and let us know your instance_id/website url. Thanks!

**Comment by jimmykane** [comment]
@julianlam  Done no worries. (was about to do so)
